<?php 

$GLOBALS['SITE'] = "BBC";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "BBC";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "BIG BOX COMPANY";
$GLOBALS[$SITE]['SYS'] = "BBC";
$GLOBALS[$SITE]['URI'] = "BBC";

// 